//
// Generated by CocoaPods-Keys
// on 23/08/2025
// For more information see https://github.com/orta/cocoapods-keys
//

#import <Foundation/NSString.h>

NS_ASSUME_NONNULL_BEGIN

@interface HibbettKeys : NSObject

@property (readonly) NSString *bazaarvoiceClientKey;
@property (readonly) NSString *bazaarvoiceStagingAPIKey;
@property (readonly) NSString *bazaarvoiceProdAPIKey;
@property (readonly) NSString *bazaarvoiceCurationsAPIKey;
@property (readonly) NSString *braintreeStagingPublicKey;
@property (readonly) NSString *braintreeProdPublicKey;
@property (readonly) NSString *hibbettDevAPIKey;
@property (readonly) NSString *hibbettStagingAPIKey;
@property (readonly) NSString *hibbettProdAPIKey;
@property (readonly) NSString *hibbettFeatureEnvAPIKey;
@property (readonly) NSString *hibbettMockEnvAPIKey;
@property (readonly) NSString *perimeterXAppID;
@property (readonly) NSString *usabillaAppID;
@property (readonly) NSString *usabillaSupportFeedbackFormID;
@property (readonly) NSString *usabillaErrorFeedbackFormID;
@property (readonly) NSString *loggerAppID;
@property (readonly) NSString *loggerAppSecret;
@property (readonly) NSString *loggerEncryptionKey;
@property (readonly) NSString *klarnaClientID;
@property (readonly) NSString *klarnaPlacementKey;
@property (readonly) NSString *siteVibesAPIKey;
@property (readonly) NSString *brazeAPIKey;
@property (readonly) NSString *brazeEndpoint;
@property (readonly) NSString *nikeClientID;
@property (readonly) NSString *movableInkAPIKey;
@property (readonly) NSString *ownIDAppID;
@property (readonly) NSString *humanAppID;
@property (readonly) NSString *hockeyAppID;
@property (readonly) NSString *instabugAPIToken;
@property (readonly) NSString *mParticleKey;
@property (readonly) NSString *mParticleSecret;
@property (readonly) NSString *narvarAccountID;
@property (readonly) NSString *narvarAuthToken;

@end

NS_ASSUME_NONNULL_END
